const GENDER = [
  { genderName: 'Male' },
  { genderName: 'Female' },
  { genderName: 'Non-Binary' },
  { genderName: 'Prefer not to say' },
];
const USER_ROLE = [
  { roleName: 'Student' },
  { roleName: 'Teacher' },
  { roleName: 'Parent' },
  { roleName: 'Staff' },
  { roleName: 'Principal' },
  { roleName: 'Librarian' },
];
const USERS = [
  {
    firstName: 'Aarav',
    lastName: 'Sharma',
    displayName: 'AaravS',
    userPhone: '9876543210',
    userEmail: 'aarav.sharma@example.com',
    gender: 'Male',
    password: 'Aarav@1234',
    userRole: 'Teacher',
    isActive: true,
    isBlocked: false,
    uniqueID: 986526,
  },
  {
    firstName: 'Rishabh',
    lastName: 'Kumar',
    displayName: 'rishabhK',
    userPhone: '9871234560',
    userEmail: 'rishabhK@example.com',
    gender: 'Male',
    password: 'Rishabh@1234',
    userRole: 'Parent',
    isActive: true,
    isBlocked: false,
    uniqueID: 869752,
  },
  {
    firstName: 'Meera',
    lastName: 'Nair',
    displayName: 'MeeraN',
    userPhone: '9998887777',
    userEmail: 'meera.nair@example.com',
    gender: 'Female',
    password: 'Meera@1234',
    userRole: 'Librarian',
    isActive: true,
    isBlocked: false,
    uniqueID: 789541,
  },
  {
    firstName: 'Rohan',
    lastName: 'Choudhary',
    displayName: 'rohanChoudhary',
    userPhone: null,
    userEmail: null,
    gender: 'Male',
    password: 'Rohan@1234',
    userRole: 'Student',
    isActive: true,
    isBlocked: false,
    uniqueID: 689402,
  },
  {
    firstName: 'Sanya',
    lastName: 'Singh',
    displayName: 'sanyaSingh',
    userPhone: '9988776655',
    userEmail: 'sanya.singh@example.com',
    gender: 'Female',
    password: 'Sanya@1234',
    userRole: 'Teacher',
    isActive: true,
    isBlocked: false,
    uniqueID: 745896,
  },
  {
    firstName: 'Kabir',
    lastName: 'Patel',
    displayName: 'kabirP',
    userPhone: null,
    userEmail: null,
    gender: 'Male',
    password: 'Kabir@1234',
    userRole: 'Student',
    isActive: true,
    isBlocked: false,
    uniqueID: 659874,
  },
  {
    firstName: 'Aisha',
    lastName: 'Khan',
    displayName: 'aishaK',
    userPhone: null,
    userEmail: null,
    gender: 'Female',
    password: 'Aisha@1234',
    userRole: 'Student',
    isActive: true,
    isBlocked: false,
    uniqueID: 598741,
  },
  {
    firstName: 'Arjun',
    lastName: 'Verma',
    displayName: 'arjunV',
    userPhone: '9988112233',
    userEmail: 'arjun.verma@example.com',
    gender: 'Male',
    password: 'Arjun@1234',
    userRole: 'Librarian',
    isActive: true,
    isBlocked: false,
    uniqueID: 523698,
  },
  {
    firstName: 'Lakshmi',
    lastName: 'Rao',
    displayName: 'lakshmiR',
    userPhone: null,
    userEmail: null,
    gender: 'Female',
    password: 'Lakshmi@1234',
    userRole: 'Student',
    isActive: true,
    isBlocked: false,
    uniqueID: 412598,
  },
  {
    firstName: 'Vikas',
    lastName: 'Mishra',
    displayName: 'vikasM',
    userPhone: null,
    userEmail: null,
    gender: 'Male',
    password: 'Vikas@1234',
    userRole: 'Student',
    isActive: true,
    isBlocked: false,
    uniqueID: 398741,
  },
];

const DEFAULT_DATA = { GENDER, USER_ROLE, USERS }
export default DEFAULT_DATA;